######
Some tests for various things I'll try in the simulations.



In [1]:
testa = {'k':300, 'c':10}
outerdict = {'cablea':testa}

In [2]:
testa['k']

300

In [5]:
outerdict['cablea']

{'k': 200, 'c': 10}

In [4]:
testa['k'] = 200

In [9]:
testb = np.array([10, 10])


In [7]:
import numpy as np

In [10]:
testb[0]

10

In [11]:
cable_tags = ['top', 'bottom', 'left', 'right']

In [12]:
cable_tags[0]

'top'

In [13]:
cabledict = {}

In [14]:
cabledict['top'] = 'test'

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
accel = np.array([2., 3., 30.])

In [28]:
accel[-1] += -9.8
accel[-1]

20.2

In [29]:
a = 0.

In [30]:
a

0.0

In [1]:
bar_r = np.array([0.05, 0.05, 0.05])
eq_pt = np.array([0.06, 0.056, 0.035])

In [2]:
bar_r - eq_pt

array([-0.01 , -0.006,  0.015])

In [3]:
print(bar_r - eq_pt)

[-0.01  -0.006  0.015]


In [4]:
shape(bar_r)

NameError: name 'shape' is not defined

In [5]:
import numpy as np

In [6]:
br = np.array(bar_r)
eq = np.array(eq_pt)

In [8]:
br.shape

(3,)

In [9]:
eq.shape

(3,)